services:
  mysql:
    image: mysql:8.0
    volumes:
      - woobuntu-finance-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./config/client.conf:/etc/nginx/conf.d/client.conf
    # depends_on:
    #   - php

volumes:
  woobuntu-finance-data:
