name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, woobuntu-finance]
    steps:
      - name: Clean up Docker resources
        run: |
          docker system prune -af --volumes

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Compose Image
        run: |
          docker compose -f /home/ubuntu/compose.yaml pull

      - name: Start Docker Compose
        run: |
          docker compose -f /home/ubuntu/compose.yaml up -d --remove-orphans
